<h1>
    SUP!!!
</h1>

<div class="row mt-3">
    <div class="col-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Preço</th>
                <tr>
            </thead>
            <tbody>
                <?php foreach ($produtos as $produto) { ?>
                <tr>
                    <td><?= $produto->id ?></td>
                    <td><?= $produto->nome ?></td>
                    <td><?= $produto->preco ?></td>
                </tr>
                <?php 
            } ?>
            </tbody>
        </table>
    </div>
</div> 